name: DECLGen
channels:
  - rdkit
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - rdkit
  - argh
  - colorama
  - scipy
  - pandas
  - seaborn
  - BioPython
  - pillow
  - statsmodels