from typing import Dict

from .BaseReport import BaseReport


class HTMLReport(BaseReport):
    template: Dict[str, str] = {}
    plots = []

    def _get_formatted_stats(self) -> str:
        formatted = []
        for stat in self.stats:
            formatted.append(self.template["stat_entry"].format(**stat))

        return "\n".join(formatted)

    def _get_formatted_table_entries(self):
        formatted = []
        for entry in self.entries:
            formatted.append(self.template["table_entry"].format(**entry))

        return "\n".join(formatted)

    def _get_formatted_other(self):
        other = []

        for plot in self.plots:
            title, content, encoding = plot

            if encoding == "text/html":
                entry = f"<h2>{title}</h2>{content}"
            else:
                entry = f"<h2>{title}</h2><div><img src=\"data:{encoding},{content}\" /></div>"

            other.append(entry)

        return "".join(other)

    def append_plot(self, title, image, encoding=None):
        if image is not None:
            self.plots.append((title, image.decode("ASCII"), "image/png;base64" if encoding is None else encoding))

    def append_plotly(self, title, html):
        self.plots.append((title, html, "text/html"))


HTMLReport.template["main"] = """<!doctype html>
<html lang="en">
	<head>
	    <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="DECL-Gen">
    
	    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        
		<title>Automatic Replicate Summary - {title}</title>
	</head>
	<body>
	    <div class="container">
	        <h1>Report - {title}</h1>
	        
	        <p class="mt-3">A quick summary over all given replicates of the same sequencing experiment.</p>
	        
	        <div class="shadow-none p-3 mb-5 bg-light rounded">
                <dl class="row" class="mt-3">
                    {stats}
                </dl>
	        </div>
			
        {other}
		
		<h2>Top hits</h2>
		
		<table class="table">
			<thead class=".thead-light">
				<tr>
					<th scope="col">Ranking</th>
					<th scope="col">Rel. counts</th>
					<th scope="col">Codon</th>
					<th scope="col">SMILES</th>
					<th scope="col">Structure</th>
				</tr>
			</thead>
			
			<tbody>
				{table_entries}
			</tbody>
		</table>
		
		</div>
		
		<footer class="bg-light mt-auto border-top">
            <p class="p-3">
                This report was automatically generated by devlEval report.
            </p>
		</footer>
		
		<!-- JavaScript for Bootstrap -->
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
	</body>
</html>
"""
HTMLReport.template["stat_entry"] = '<dt class="col-sm-3">{name}</dt><dd class="col-sm-9">{value}</dd>'
HTMLReport.template["table_entry"] = """<tr>
    <th scope="row">{rank}</th>
    <td>{count:.2f}</td>
    <td>{codon}</td>
    <td>{smiles}</td>
    <td><img height="200px" src="data:mage/png;base64,{imgb64}" /></td>
</tr>
"""
