from typing import Dict

from .BaseReport import BaseReport

class HTMLReport(BaseReport):
    template: Dict[str, str] = {}
    def _get_formatted_stats(self) -> str:
        formatted = []
        for stat in self.stats:
            formatted.append(self.template["stat_entry"].format(**stat))

        return "\n".join(formatted)

    def _get_formatted_table_entries(self):
        formatted = []
        for entry in self.entries:
            formatted.append(self.template["table_entry"].format(**entry))

        return "\n".join(formatted)



HTMLReport.template["main"] = """<!DOCTYPE html>
<html>
	<head>
		<style>
			body {{
				font-family: "Latin Modern Sans", "Arial", sans-serif;
			}}
			
			dl {{
			}}
			
			dl dt {{
				font-weight: bold;
				float: left;
				width: 20em;
			}}
			
			dl dt:after {{
				content: ":";
			}}
			
			table {{
				border-collapse: collapse;
			}}
			
			thead th, tbody td {{
				padding: 1em;
				border-top: 1px solid black;
				border-bottom: 1px solid black;
			}}
			
			tbody tr:last-child td {{
				border-bottom: 1px solid black;
			}}
			
			.smiles {{
				font-family: "Latin Modern Mono", "Courier New", monospace;
			}}
		</style>
		<title>Report - {title}</title>
	</head>
	<body>
		<h1>Report - {title}</h1>
		<h2>Statistics</h2>
			<dl>
			    {stats}
			</dl>
		
		<h2>Top hits</h2>
		<table>
			<thead>
				<tr>
					<th>Ranking</th>
					<th>RelCounts</th>
					<th>codons</th>
					<th>SMILES</th>
					<th>Structure</th>
				</tr>
			</thead>
			
			<tbody>
				{table_entries}
			</tbody>
		</table>
		
		<p>
		    This report was automatically generated by devlEval report.
		</p>
	</body>
</html>
"""
HTMLReport.template["stat_entry"] = "<dt>{name}</dt><dd>{value}</dd>"
HTMLReport.template["table_entry"] = """<tr>
    <td>{rank}</td>
    <td>{count}</td>
    <td>{codon}</td>
    <td class="smiles">{smiles}</td>
    <td><img src="data:image/png;base64,{imgb64}" /></td>
</tr>
"""